mirror-main:
  image:
    name: alpine:3
  variables:
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ecdsa-gitlab-ci"
    GIT_STRATEGY: clone
  script:
    - apk add --no-cache git openssh
    - git checkout master
    - git rebase origin/main
    - mkdir -pvm 0700 ~/.ssh
    - echo "$SSH_DEPLOY_KEY" > ~/.ssh/id_ecdsa-gitlab-ci
    - chmod 0400 ~/.ssh/id_ecdsa-gitlab-ci
    - git remote set-url origin git@gitlab.com:${CI_PROJECT_PATH}.git
    - git push origin master
  only:
    - main
