on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory"
        default: "./"
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ${{ inputs.working-directory }}
  test:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ${{ inputs.working-directory }}/go.mod
          cache-dependency-path: ${{ inputs.working-directory }}/go.sum
      - name: Run tests
        run: go test ./...
