AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "**/*_pb.rb"

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "**/*.rake"
    - "db/**/*.rb"
    - "**/spec/**/*.rb"
    - "**/*.gemspec"
Metrics/ClassLength:
  Max: 1500
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/**/*.rb"
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/PerceivedComplexity:
  Max: 20

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
Layout/LineLength:
  Max: 160
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/MultilineIfModifier:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/Semicolon:
  AllowAsExpressionSeparator: true
Style/SingleLineBlockParams:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# TODO: review after v1 is released
# ---------------------------------------------------------------------

Style/HashEachMethods: # (0.80)
  Enabled: true
Style/HashTransformKeys: # (0.80)
  Enabled: true
Style/HashTransformValues: # (0.80)
  Enabled: true
Lint/RaiseException: # (0.81)
  Enabled: true
Lint/StructNewOverride: # (0.81)
  Enabled: true
Layout/SpaceAroundMethodCallOperator: # (0.82)
  Enabled: true
Style/ExponentialNotation: # (0.82)
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor: # (0.83)
  Enabled: true
Style/SlicingWithRange: # (0.83)
  Enabled: true
Lint/DeprecatedOpenSSLConstant: # (0.84)
  Enabled: true
Lint/MixedRegexpCaptureTypes: # (0.85)
  Enabled: true
Style/RedundantRegexpCharacterClass: # (0.85)
  Enabled: true
Style/RedundantRegexpEscape: # (0.85)
  Enabled: true
