on:
  workflow_call:
    inputs:
      context:
        description: "The Docker context"
        default: "."
        type: string
      file:
        description: "Path to Dockerfile"
        type: string
      image:
        description: "The image name"
        default: ghcr.io/${{ github.repository }}
        type: string
      tags:
        description: "List of tags as key-value pair attributes https://github.com/docker/metadata-action/?tab=readme-ov-file#tags-input"
        type: string
      labels:
        description: "List of custom labels https://github.com/docker/metadata-action/?tab=readme-ov-file"
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ inputs.image }}
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
